name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!" 
      - name: What time is it?
        run: |
          date
      - name: Who am I?
        run: |
          whoami
      - name: List directory
        run: |
          ls -l
