name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!" 
          echo "The time is $(date)"
          echo "The user is $(whoami)"
          echo "The current directory has $(ls -l)"